apiVersion: v1
kind: Service
metadata:
  name: project2-backend-service
spec:
  type: NodePort
  selector:
    app: project2-backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
