apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project2
  template:
    metadata:
      labels:
        app: project2
    spec:
      containers:
      - name: project2
        run: docker build -t apoorva861/project_2:dev ./backend
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: project2-service
spec:
  selector:
    app: project2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
